### DISCUSSION TITLE
Logs not showing color

### DISCUSSION THREAD

**Discussion by nycdavid** [F1bonacc1/process-compose#181] [Q&A] [answered]
I have a `process-compose.yml` file that looks like this:

```yaml
version: "0.5"

processes:
  server:
    command: go run main.go
  webpack:
    command: yarn run webpack --watch
```

The color in the webpack logs doesn't seem to coming through when running through process-compose. I would have expected this:

<img width="564" alt="Screenshot 2024-05-02 at 9 33 48 AM" src="https://github.com/F1bonacc1/process-compose/assets/442265/348d62c3-81d7-41b4-8ffd-21f13409a184">

but instead get this:

<img width="567" alt="Screenshot 2024-05-02 at 9 36 12 AM" src="https://github.com/F1bonacc1/process-compose/assets/442265/c65e65cb-3f97-4c09-becc-903dfbd5043b">

The output is always decolorized whether the `disable_ansi_colors` value is set to `true` or `false`.

Is there any additional configuration that needs to happen for this color to come through?

process-compose v1.2.0
installed via brew

**Comment by F1bonacc1** [comment, marked as answer]
Hey @nycdavid,

I guess that webpack is looking for `tty` to output colors.
Can you change your `process-compose.yaml` to:
```yaml
version: "0.5"

processes:
  webpack:
    command: yarn run webpack --watch
    is_tty: true  # add this line
```
and try again?
