### DISCUSSION TITLE
v0.55.0-RC1

### DISCUSSION THREAD

**Discussion by F1bonacc1** [F1bonacc1/process-compose#66] [Announcements]
#  ⚠️ BETA version ⚠️

# What Changed
* Added the ability to start multiple replicas of a process (Issue #61)
```yaml
processes:
  process_name:
    command: "sleep 2"
    log_location: ./log_file.{PC_LOG}.log  # <- {PC_LOG} will be replaced with replica number. If more than one replica and PC_LOG not specified, the replica number will be contaminated to the file end.
    replicas: 2  # <- NEW
```
* Added the ability to scale processes on the fly from TUI, CLI, REST or process-compose in Client mode (`process-compose attach`)
```shell
process-compose process scale process_name 3
```
* Added ability to review process used ports (Issue #62)
* Added check to prevent circular dependencies between processes
* Added exit code 1 and proper message (not only to the log) in case of CLI command failure

<hr /><em>This discussion was created from the release <a href='https://github.com/F1bonacc1/process-compose/releases/tag/v0.55.0'>v0.55.0-RC1</a>.</em>
