### DISCUSSION TITLE
v0.60.0

### DISCUSSION THREAD

**Discussion by F1bonacc1** [F1bonacc1/process-compose#81] [Announcements]
# What Changed
- Added the ability to start multiple replicas of a process (Issue https://github.com/F1bonacc1/process-compose/discussions/61)
```yaml
processes:
  process_name:
    command: "sleep 2"
    log_location: ./log_file.{PC_REPLICA_NUM}.log  # <- {PC_REPLICA_NUM} will be replaced with replica number. If more than one replica and PC_REPLICA_NUM is not specified, the replica number will be concatenated to the file end.
    replicas: 2  # <- NEW
```

- Added the ability to scale processes on the fly from TUI (F2), CLI, REST or process-compose in Client mode (process-compose attach)
- process-compose process scale process_name 3
- Added ability to review process used ports (F3) (Issue #62)
- Added ability to stop a list of processes (Issue #65)
- Added ability to shut down only the parent process (Issue #67). ❤️ @airwoodix 
- Added ability to specify the log file path `--logFile` flag or `PC_LOG_FILE` environment variable (Issue #70)
- Missing directories/for/log will be automatically created (Issue #71) ❤️ @airwoodix 

- Added ability to shut down Process Compose when the specified process completes its task (Issue #77) ❤️ @adrian-gierakowski 
- Added check to prevent circular dependencies between processes

## Bug Fixes
- Running more than one Process Compose process on the same port is no longer possible (Issue #68)
- Added exit code 1 and proper message (not only to the log) in case of CLI command failure (Issue #69)
- Added `working_dir` definition to `liveness_probe` or `readiness_probe` `exec`. If not defined, the working dir of the process will be used (Issue #72)
- TUI special characters in log are now escaped. ❤️ @enobayram

## Changelog
* 08ddae9 Circular dependency check
* f422f37 Escape the TUI log lines in ANSI color mode
* 43ac3cc Fix the scale swagger description
* c51b8a7 Get Process Ports
* 9fb6eaa Scale tests
* e9b02c5 Scaling Support
* d510325 add arm64 support to netstat
* a632c49 add working dir to probe exec
* c191885 config: add process.shutdown.parent_only option.
* 6ff27e0 configurable log file path
* 89faad4 fatal on port in use
* bd60041 feat: availability.exit_on_end (#78)
* 1809c0d fix missing process list and no-deps in up cmd
* ed79278 fix restart process race condition
* 328fecd logger: create parent directories if necessary
* 32f5647 msg and exit code 1 on cli error
* e81bc97 stop multiple processes with a single command

<hr /><em>This discussion was created from the release <a href='https://github.com/F1bonacc1/process-compose/releases/tag/v0.60.0'>v0.60.0</a>.</em>
