### ISSUE TITLE
Turn default TUI toggles to verbs to avoid confusion

### ISSUE THREAD

**Issue by thenonameguy** [F1bonacc1/process-compose#101]
## Feature Request

![image](https://github.com/F1bonacc1/process-compose/assets/2217181/15f868e0-c94a-48ac-9851-d50166c560a0)

Currently some of the labels of TUI actions can be interpreted as representing the current state of the TUI, instead of the action that will happen when the button is pressed.

Example: the LOGS section 'Follow Off' button.
The verb 'Unfollow' would make it less ambiguous what happens.

#### Use Case:
Day to day TUI usage. First time users sometimes got confused, from anecdotal evidence.

#### Proposed Change:
Only use verbs for actions.

#### Who Benefits From The Change(s)?
All TUI users.

#### Alternative Approaches
The existing [shortcuts config](https://github.com/F1bonacc1/process-compose/wiki/Shortcuts-Configuration) can resolve this on a case-by-case basis, but is cumbersome for first-time users to do.

**Comment by thenonameguy** [comment]
Proposed defaults:
```
shortcuts:
  log_follow: # action name - don't edit
    toggle_description: # optional description for toggle buttons. Will use default if not defined
      false: Unfollow
      true: Follow
    shortcut: F5 # shortcut to be used
  log_screen:
    toggle_description:
      false: Minimize
      true: Maximize
    shortcut: F4
  log_wrap:
    toggle_description:
      false: Unwrap
      true: Wrap
    shortcut: F6
  process_restart:
    description: Restart # optional description for a button. Will use default if not defined
    shortcut: Ctrl-R
  process_screen:
    toggle_description:
      false: Minimize
      true: Maximize
    shortcut: F8
  process_start:
    description: Start
    shortcut: F7
  process_stop:
    description: Stop
    shortcut: F9
  quit:
    description: Quit
    shortcut: F10
```
