### ISSUE TITLE
non-wrapped stdout/stderr tee'd to a file

### ISSUE THREAD

**Issue by colemickens** [F1bonacc1/process-compose#109]
## Feature Request
I would like to be able to specify something like this:

```
log_configuration:
  no_wrap: true

processes:
  foo:
    command: echo "test" | tee /dev/stderr
    log:
      stdout: ./state/foo.stdout
      stderr: ./state/foo.stderr
  bar:
    command: echo "test" | tee /dev/stderr
    log:
      stdouterr: ./state/bar.log
```

to get non-wrapped direct output from commands being run.

that might not be the right config api, but it expresses what I'd like to be able to achieve.

I can't seem to disable some sort of extra log wrapping otherwise?

#### Use Case:

Be able to use direct application logout, unmodified. For further processing, other tools, etc.

#### Proposed Change:

see described config

#### Who Benefits From The Change(s)?

A user who would like to use process-compose without needing to do output tee-ing themselves in every process usage where they want logs after the fact.

Also, I and some others have seen some hangs from something we run in process-compose that requires tearing it down. It would be great to have the raw logs to look at afterward.

**Comment by F1bonacc1** [comment]
Hi @colemickens,

Thank for trying PC.
You can try something like this:

```yaml
processes:
  foo:
    command: "echo test"
    log_location: ./foo.log
    log_configuration:
      no_metadata: true
      fields_order: ["message"]
      disable_json: true
```
https://f1bonacc1.github.io/process-compose/logging/#logger-configuration
