### ISSUE TITLE
Does the plan support one-time scripts?

### ISSUE THREAD

**Issue by cevin** [F1bonacc1/process-compose#12]
like systemd  `Type=oneshot`

just run once on boot.

**Comment by F1bonacc1** [comment]
Yes this is the default mode. If you want to define it explicitly, you can do something like:
```yaml
process_name:
  command: "echo Hi"
  availability:
    restart: no  # <-- "no" is the default if not specified
```
