### ISSUE TITLE
Weird interpolation with environment: script not working

### ISSUE THREAD

**Issue by pmiddend** [F1bonacc1/process-compose#120]
I have the following `yml` file which I feed into `process-compose up`:

```yaml
version: "0.5"

environment:
  - "I_AM_GLOBAL_EV=5"

processes:
  process1:
    description: This process will sleep for 2 seconds
    command: "echo $I_AM_GLOBAL_EV > /tmp/output"
```

This leads to a `/tmp/output` file being generated - but it's empty. Why is that? If I execute `env` and redirect it, I see the variable.

**Comment by F1bonacc1** [comment]
Hi @pmiddend 

This is the expected behavior. What happens:
1. The env variables engine looks for `$I_AM_GLOBAL_EV` env variable and replaces `$I_AM_GLOBAL_EV` with its value.
2. The env variable is not found either in the environment or in `.env` file.
3. `$I_AM_GLOBAL_EV` is converted to an empty string.
4. The `I_AM_GLOBAL_EV=5` is fed into the echo process where it is not used because of 3.

To achieve the functionality that you are after I would recommend using either `.env` [file](https://f1bonacc1.github.io/process-compose/configuration/#env-file) or [vars](https://f1bonacc1.github.io/process-compose/configuration/#variables).

### Using `.env` file
```
I_AM_GLOBAL_EV=5
```
### Using vars
```yaml
version: "0.5"

vars:
  I_AM_GLOBAL_EV: 5

processes:
  process1:
    description: This process will sleep for 2 seconds
    command: "echo {{ .I_AM_GLOBAL_EV }} > /tmp/output"
```

P.S.
Before answering you I tested the configuration and found a small bug. It is fixed now in v0.77.6. If you'll go with the vars direction, better use the new version.

**Comment by pmiddend** [comment]
What a thorough explanation, thank you very much!

**Comment by teto** [comment]
I dont get it, what does global environment do then ? 

> The env variables engine looks for $I_AM_GLOBAL_EV env variable and replaces $I_AM_GLOBAL_EV with its value.

why does it do that instead of just running the command with environment variables injected in the process ?

Referring to your example in 2) why doesn't process-compose find the 
https://f1bonacc1.github.io/process-compose/configuration/

**Comment by r7vme** [comment]
Thanks for the tool, I find it really useful!

However it is not clear from the explanation (from @F1bonacc1 ) above what is the purpose of `environment` then. I expect example from the description to produce `5` in `/tmp/output`. [Similar to `tmuxp` tool ](https://tmuxp.git-pull.com/configuration/examples.html#environment-variables). This is really useful feature many applications.

Thanks, Roman

**Comment by adrian-gierakowski** [comment]
> Thanks for the tool, I find it really useful!
> 
> However it is not clear from the explanation (from @F1bonacc1 ) above what is the purpose of `environment` then. I expect example from the description to produce `5` in `/tmp/output`. [Similar to `tmuxp` tool ](https://tmuxp.git-pull.com/configuration/examples.html#environment-variables). This is really useful feature for many applications.
> 
> Thanks, Roman

Stuff you set in environment is present in env during runtime. You can test it by calling env in you script, or by putting your script into an executable file instead of inlining it. The confusing part is the PC does $ variable substitution within the config file at load time so the vars in your inline script are replaced with their values from env (or empty if they are not set) before the script is even ran. The worst part is that there is no way to escape it, which handicaps the usability of inline scripts in PC config files. Hence I never do that and always put scripts in their own files.

**Comment by cdmistman** [comment]
> The worst part is that there is no way to escape it, which handicaps the usability of inline scripts in PC config files.

i was bit by this badly yesterday, trying to figure out why a script that i was writing like `fswatch ... | while read file; do echo "found file $file"; done` wasn't printing anything with pc, but was with inline commands and scripts. thanks for the explanation!

since fixing the templating would be a breaking change (major even?) it would be beneficial to mention this shortcoming in the docs to save others pain. i can open a PR later if nobody beats me to it

**Comment by F1bonacc1** [comment]
Will it help if I add the ability to escape env variables with `$$`?
```yaml
foo:
  command: "echo log is $$ENV_TEST"
  environment:
    - 'ENV_TEST=ready'
```
Output: `log is ready`
