### ISSUE TITLE
request: process groups in a single yaml file

### ISSUE THREAD

**Issue by colemickens** [F1bonacc1/process-compose#131]
## Feature Request

We have different scenarios for which we run our app:
* basic setup
* load balanced setup with two app instances, and a reverse proxy

For now, we add in default-disabled commands, or copy/paste/edit the process-compose file to enable these various scenarios.

However, I can imagine a concept of "process groups" (a group of pre-declared tasks maybe), that would allow us to DRY and have these scenarios/configs declared in a single YAML file

#### Use Case:

* Single-file config, removing duplication from similar configurations

#### Proposed Change:

* Add another layer/concept to enable named groups of processes/tasks inside the yaml file to be run by user choice.

#### Who Benefits From The Change(s)?

Users

#### Alternative Approaches

Lots of separate files, using advanced yaml features inclusions, etc. All of these are subpar options, in my view.

**Comment by F1bonacc1** [comment]
Hi @colemickens,

Have you considered using the merge functionality of process compose?
https://f1bonacc1.github.io/process-compose/merge/

**Comment by thenonameguy** [comment]
Agreed with @F1bonacc1, that should be the correct way to do it.
So in the end you do something like:
```
process-compose --tui=false up -f process-compose.yml -f process-compose.load-balanced.yml
```

**Comment by colemickens** [comment]
While I appreciate the answer, the UX for all of this feels... undesirable, compared to what I was suggesting. I'm thinking about hacking on this myself and seeing what I come up with. Or maybe an alternative approach as a zellij plugin. I really don't mean to sound ungrateful and I wish I could better articulate why I feel the way I do about the UX. Maybe I'll come up with some more examples and try out how it feels.

**Comment by stijnveenman** [comment]
i think we have a similar situation. Have multiple vertical slices that we run separately (we use `process-compose` for our local dev env). So we define multiple tasks for each vertical slice. With an 'empty' command, which could just be `echo "done"`, or in our case, open the web page of the vertical slice when startup is complete. 

```yaml
  group1:
    command: open http://localhost:1080/group1
    depends_on:
      process1: { condition: process_started }
      process2: { condition: process_started }

  group2:
    command: open http://localhost:1080/group2
    depends_on:
      process1: { condition: process_started }
      process3: { condition: process_started }
```

could this be an alternative approach? this allows for a simple `process-compose up group1` or both `process-compose up group2` while allowing processes to still be used in multiple groups (unlike namespaces for example)
