### ISSUE TITLE
Is it possible to set variables in process.command ? 

### ISSUE THREAD

**Issue by teto** [F1bonacc1/process-compose#151]
in my tests, I run:
```
# This starts a temp postgres, that displays its connection on stdout (https://github.com/eradman/ephemeralpg)
POSTGRESQL_CONNECTION="$(pg_tmp)" 
# start my own service
my-service --database $POSTGRESQL_CONNECTION 
```
and I am trying to replicate this in process-compose (which I've just discovered and absolutely love, this is going to improve my workflow tenfolds):
```
processes:
  postgresql:
    command:
       POSTGRESQL_CONNECTION="$(pg_tmp)" # ofc that would't work ?
  my_service:
    command:
       my-service --database $POSTGRESQL_CONNECTION
```
One possible workaround could be to write $POSTGRESQL_CONNECTION into a file and read its value from the my_service process.

Maybe even easier would be to just ditch pg_tmp and start a proper `postgresql` directly. I was curious though what was possible/usually done
