### ISSUE TITLE
problem loading shortcuts

### ISSUE THREAD

**Issue by teto** [F1bonacc1/process-compose#152]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] Included the relevant configuration snippet
- [x] Included the relevant process-compose log (log location: `process-compose info`)
- [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

```
➜ cat ~/.config/process-compose/shortcuts.yaml
shortcuts:
  process_stop:
    description: Terminate
  quit:
    shortcut: q
```

```
❯ /nix/store/lb2b16q8kc3xynj27d25sahhq95ph43h-process-compose-0.88.0/bin/process-compose info
Process Compose
Logs:           /tmp/nix-shell.wJN9EN/process-compose-teto.log
Shortcuts:      /home/teto/.config/process-compose/shortcuts.yaml
```

#### Version of `process-compose`:

Looks like this could be included in `process-compose info`:
````
/nix/store/lb2b16q8kc3xynj27d25sahhq95ph43h-process-compose-0.88.0/bin/process-compose version
Process Compose
Version:        v0.88.0
Commit:         82b51ba
Date (UTC):     2024-03-02T19:47:22Z
License:        Apache-2.0
Discord:        https://discord.gg/S4xgmRSHdC

Written by Eugene Berger
```

#### OS environment:
nixos-unstable

#### Steps or code to reproduce the issue:
I've just added this file
```
cat ~/.config/process-compose/shortcuts.yaml
shortcuts:
  process_stop:
    description: Terminate
  quit:
    shortcut: q
```

I've added `strace -olog /nix/store/lb2b16q8kc3xynj27d25sahhq95ph43h-process-compose-0.88.0/bin/process-compose`
and looking at the log, it seems to look at 
```
751793 newfstatat(AT_FDCWD, "/home/teto/.config/process-compose/shortcuts.yaml",  <unfinished ...>
```
but still `q` doesn't quit and F1 lists F10 as a shortcut.
Thanks to this issue, I found out about the log file but it just prints
`[90m24-03-07 13:34:38.831[0m [32mINF[0m [1mProcess Compose v0.88.0[0m`
I haven't found a way to increase logging (like `--debug` or `-vvv` or `--log-level=debug`) but it would be nice to have a message like
"Loaded shortcuts from ..../shortcuts.yaml" / "No shortcuts.yaml found"

#### Expected result:
exit the program with `q` instead of `F10`
#### Actual result:
`f10` to quit the program

This is weird that it doesn't load. I feel like there must be something fishy with my config but I dont find why. Also it's the occasion to improve the logging
