### ISSUE TITLE
environment variable not taken into account in readyness probe.exec

### ISSUE THREAD

**Issue by teto** [F1bonacc1/process-compose#155]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] Included the relevant configuration snippet
- [x] Included the relevant process-compose log (log location: `process-compose info`)
- [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

In my process-compose.yaml I have
```
# top level environment 
environment:
  - "POSTGRESQL_PORT=15432"

processes:
  my_service:
   ....
    readiness_probe:
      exec:
        command:
          # the probe fails, nothing is logged so I can't diagnose (I should probably try strace)
          # but if I replace ${POSTGRESQL_PORT} with its value aka 15432 then the probe works
          # so I suspect it's not interpolated
          pg_isready -h 127.0.0.1 -p ${POSTGRESQL_PORT}
```

#### Version of `process-compose`:
0.88
```
$ process-compose info
Process Compose
Logs:           /tmp/nix-shell.WDtwSi/process-compose-teto.log
Shortcuts:      /home/teto/.config/process-compose/shortcuts.yaml
```
#### OS environment:
nixos-unstable

#### Steps or code to reproduce the issue:
see previous config

#### Expected result:
have `pg_isready -h 127.0.0.1 -p ${POSTGRESQL_PORT}` interpolated into `pg_isready -h 127.0.0.1 -p 15432`.
I see in the doc there is something called `VARS`. It looks related to the templated engine so it looks orthogonal ?
I am not sure why processes has `command` while the probe has `exec`. Is it because of this difference in behavior ?
It would be helpful to see the actual probe commands in a DEBUG log level mode.

#### Actual result:
I suspect it's not interpolated and thus the probe fails
