### ISSUE TITLE
body.fgColor applies to dialog text instead of process output

### ISSUE THREAD

**Issue by scottjad** [F1bonacc1/process-compose#167]
With the following theme:
```yaml
style:
  body:
    fgColor: green
  dialog:
    fgColor: red
```

I see the green in dialog text and process output remains white. I expected the white text in the screenshot below to be green.

![image](https://github.com/F1bonacc1/process-compose/assets/124373/489f040c-4846-4f17-9f89-8882b3ed6547)

Thanks for the theming support!
