### ISSUE TITLE
Unable to override `disabled` option

### ISSUE THREAD

**Issue by Invizory** [F1bonacc1/process-compose#177]
## Defect

[“Adding and overriding configuration” section in the documentation](https://f1bonacc1.github.io/process-compose/merge/#adding-and-overriding-configuration) states:

> For single-value options like `command`, `working_dir` or `disabled`, the new value replaces the old value.

However, the old value of `disabled` is not actually replaced if the new value is `false`.

#### Version of `process-compose`:

1.2.0

#### OS environment:

Ubuntu 22.04.4 LTS

#### Steps or code to reproduce the issue:

`process-compose.yml`:

```yml
version: "0.5"
processes:
  test:
    disabled: true
    command: echo foo
```

`process-compose.override.yml`:

```yml
processes:
  test:
    disabled: false
    command: echo bar
```

Run `process-compose run test`.

#### Expected result:

```
bar
```

#### Actual result:

```
```
