### ISSUE TITLE
ENV VAR is not captured similar to docker compose

### ISSUE THREAD

**Issue by dephiros** [F1bonacc1/process-compose#179]
I have some env var set through direnv and try to get process-compose to pick them up similar to how docker-compose handle them in this doc: https://docs.docker.com/compose/compose-file/05-services/#environment(`DYLD_LIBRARY_PATH` will use the value from the current shell)

```
# Process compose for starting django
version: "0.5"

processes:
  django:
   command: echo Value of env $DYLD_LIBRARY_PATH
   environment:
    - DYLD_LIBRARY_PATH
   availability:
    restart: "always"
```
Appreciate any help or pointer

**Comment by dephiros** [comment]
Figured out this is related to Apple SIP: https://hynek.me/articles/macos-dyld-env/
Any suggestion for workaround would be greatly appreciated

**Comment by adrian-gierakowski** [comment]
@dephiros 

please see: https://github.com/F1bonacc1/process-compose/issues/120#issuecomment-2054137325

**Comment by F1bonacc1** [comment]
Hi @dephiros 

Is `DYLD_LIBRARY_PATH` env variable defined in the `PC` shell?
If not `command: echo Value of env $DYLD_LIBRARY_PATH` will be converted to `command: echo Value of env`.

The environment syntax is:
```yaml
processes:
  django:
   command: echo Value of env $DYLD_LIBRARY_PATH
   environment:
    - key=value # <---
   availability:
    restart: "always"
```
But this won't help if  `DYLD_LIBRARY_PATH` is not defined. See comment: https://github.com/F1bonacc1/process-compose/issues/120#issuecomment-1858002134

Depending on your use case, consider using [vars](https://f1bonacc1.github.io/process-compose/configuration/#variables) instead.
