### ISSUE TITLE
PTY for process 'process0' is not yet supported on Windows

### ISSUE THREAD

**Issue by senpro-ingwersenk** [F1bonacc1/process-compose#245]
Hello there!

I am aware that Windows support isn't complete yet, so I wanted to ask what the status was on this?

Here is the process-compose file that triggered the error:

```yaml
version: "0.5"
processes:
  db:
    description: SurrealDB Database
    command: surreal start
    readiness_probe:
      exec:
        command: surreal is-ready
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    liveness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http_getpath: /
        port: 8000
      initial_delay_seconds: 5
      period_seconds: 2
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    vars:
      # Settings
      - "SURREAL_NO_BANNER=true"
      - "SURREAL_STRICT=true"
      - "SURREAL_PATH=file:./runtime/db"
      - "SURREAL_CLIENT_IP=socket"
      - "SURREAL_CAPS_DENY_GUESTS=false"
      # Authentication
      - "SURREAL_AUTH=true"
      - "SURREAL_USER=db"
      - "SURREAL_PASS=db"
  
  app:
    command: ./dsb-tool.exe
    depends_on:
      db:
        condition: process_healthy
  
  app-dev:
    command: air
    depends_on:
      db:
        condition: process_healthy

  vite:
    command: vite
```

It's nothing too special, but due to how the restrictiions on our work laptops are, Docker and Podman have issues - so I sought to just deploy the environment locally...ish. :)

thank you and kind regards!
