### ISSUE TITLE
PC_REPLICA_NUMBER not available as environment variable

### ISSUE THREAD

**Issue by l-monninger** [F1bonacc1/process-compose#248]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] Included the relevant configuration snippet
- [x] Included the relevant process-compose log (log location: `process-compose info`)
- [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Steps or code to reproduce the issue:

```yml
# process-compose.yml
version: "1.27"

processes:

  say-replica-num:
    command: |
     echo $PC_REPLICA_NUM
    replicas: 2
```

Run:
```shell
process-compose up -t=false
```

#### Expected result:

```shell
[say-replica-num-1      ] 1 
[say-replica-num-0      ] 0
```

#### Actual result:

```shell
[say-replica-num-1      ] 
[say-replica-num-0      ] 
```

**Comment by l-monninger** [comment]
Further, the whole environment does not appear to be working...

```shell
# process-compose.yml
version: "1.27"

processes:

  say-replica-num:
    environment:
      - "PC_REPLICA_NUM=1"
    command: |
     echo $PC_REPLICA_NUM
```

**Comment by F1bonacc1** [comment]
Duplicae of #120 
Also please check the [documentation](https://f1bonacc1.github.io/process-compose/configuration/#disable-automatic-expansion).

**Comment by F1bonacc1** [comment]
From docs:
```yaml
processes:

  say-replica-num:
    command: |
     echo $$PC_REPLICA_NUM
    replicas: 2
```
