### ISSUE TITLE
Stuck forever in `down` command (despite `shutdown.timeout_seconds`)

### ISSUE THREAD

**Issue by mprimi** [F1bonacc1/process-compose#258]
This is a follow-up to https://github.com/F1bonacc1/process-compose/issues/251 where i was seeing call to `list` getting stuck. Since then I have added a `shutdown.timeout_seconds` parameter to ensure timely shutdown.
However I am now seeing `down` getting stuck forever, e.g..:
```
$ ps aux | grep process-compose
myuser  480743  0.1  1.1 1917956 44684 pts/1   Sl+  15:48   0:13 process-compose -L /[...]/process-compose.log --config ./config/[...].yml --port 18080 --tui=false up
myuser  481605  0.0  0.9 1622260 37120 pts/1   Sl+  15:53   0:00 process-compose --port 18080 down
```

In this configuration, i am running 6 processes.
 - 5 of them shut down without issue
 - 1 of them is still alive under that `up` command.

I expected `shutdown.timeout_seconds` (set to 5 seconds) to kick in and KILL the culprit.
However the `down` process has been stuck where it is for the last hour.

---

```
$ sudo cat /proc/480743/stack
[<0>] futex_wait_queue+0x67/0xa0
[<0>] futex_wait+0x151/0x270
[<0>] do_futex+0x178/0x230
[<0>] __x64_sys_futex+0x78/0x1f0
[<0>] x64_sys_call+0x1c47/0x2570
[<0>] do_syscall_64+0x56/0x90
[<0>] entry_SYSCALL_64_after_hwframe+0x73/0xdd
```

```
 sudo $(which gdb) -batch -ex bt $(which process-compose) 480743
[New LWP 481115]
[New LWP 480892]
[New LWP 480751]
[New LWP 480750]
[New LWP 480749]
[New LWP 480748]
[New LWP 480747]
[New LWP 480746]
[New LWP 480745]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libthread_db.so.1".
0x0000000000476c43 in ?? ()
#0  0x0000000000476c43 in ?? ()
#1  0x000000000043b830 in ?? ()
#2  0x0000000001cc2020 in ?? ()
#3  0x0000000000000080 in ?? ()
#4  0x0000000000000000 in ?? ()
[Inferior 1 (process 480743) detached]
```

Unfortunately not much to go on here...

---

Current repro (maybe you can repro this yourself):
 - Create configuration with multiple processes
 - Set `shutdown.timeout_seconds` for all of them
 - Modify one of the processes to ignore SIGTERM (e.g. force the shutdown to timeout and issue a SIGKILL)
 - Start-stop a few times and possibly observe `down` getting stuck

This is reproducing for me with  v1.27 on Linux.

Happy to capture any more data you think is interesting, or to try other configuration settings.

**Comment by F1bonacc1** [comment]
Hi @mprimi,

Thank you for such a detailed analysis, this is very helpful.
I created this project:
```yaml
version: "0.5"
log_level: info
log_length: 300

processes:
  pc_log:
    command: "tail -f -n100 process-compose-${USER}.log"
    working_dir: "/tmp"
    shutdown:
      timeout_seconds: 5

  sigterm_resistant:
    command: "trap '' SIGTERM && sleep 20"
    shutdown:
      timeout_seconds: 5

  sleeper:
    command: "sleep 60"
    replicas: 5
    shutdown:
      timeout_seconds: 5
```
Started it about 20 times and stopped it with the `down` command. Each time the project stopped as expected.
This is the script I used:
```shell
for i in {1..20} ; do ./bin/process-compose up -f issues/issue_258/process-compose.yaml -t=false & sleep 1 && ./bin/process-compose down ; done
```
Are there any additional details we might have missed?
Maybe there is something specific to your `process-compose.yaml`? Would you be able to publish it or try to repro with mine?

**Comment by mprimi** [comment]
Thank you for looking into this. 

I also have been trying to repro with a variant of `TestSystem_TestProcShutDownWithConfiguredTimeOut`, unsuccessfully so far.

Nevertheless our CI pipes (1.27 on Linux via `nix`) get stuck daily on `up` and `down` blocked on one process that doesn't shut down.

I'll keep trying to see if i can learn more from it and report back.

Here's a snip of the configuration I'm using:

```
  Server_s1:
    namespace: "cluster"
    command: "[...]/server -c ./config/s1.conf"
    log_location: /tmp/s1.log
    working_dir: "."
    availability:
      restart: "always"
    liveness_probe:
      initial_delay_seconds: 5
      period_seconds: 1
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/"
        port: 18221
    readiness_probe:
      initial_delay_seconds: 5
      period_seconds: 1
      timeout_seconds: 2
      success_threshold: 1
      failure_threshold: 8
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/health"
        port: 18221

(more servers with the same configuration omitted)
```

**Comment by F1bonacc1** [comment]
This is very helpful.
I suspect it might be related to the readiness probe not being `Ready` when the `down` command is issued.
I will find time soon to confirm and fix it.

**Comment by Lagoja** [comment]
We're seeing a similar issue with Devbox using our process-compose.yaml for Postgresql:

```
version: "0.5"

processes:
  postgresql:
    command: "pg_ctl start -o \"-k $PGHOST\""
    is_daemon: true
    shutdown:
      command: "pg_ctl stop -m fast"
    availability:
      restart: "always"
    readiness_probe:
      exec:
        command: "pg_isready"
```
