### ISSUE TITLE
Crashes and exits without error message when unknown process is in `depends_on` section.

### ISSUE THREAD

**Issue by j-chmielewski** [F1bonacc1/process-compose#261]
## Defect

Process-compose exits with non-zero exit status when unknown process is in `depends_on` section. To reproduce:

```yaml
version: "0.5"

processes:
  a:
    command: echo "ready" && sleep 1000
    ready_log_line: "ready"
    depends_on:
      c:
        condition: process_log_ready

  b:
    command: echo "ready" && sleep 1000
    ready_log_line: "ready"
```

#### Version of `process-compose`:

1.34.0

#### OS environment:

Linux blade 6.6.53 #1-NixOS SMP PREEMPT_DYNAMIC Mon Sep 30 14:25:15 UTC 2024 x86_64 GNU/Linux
