### ISSUE TITLE
add possibility to skip the exit confirmation prompt 

### ISSUE THREAD

**Issue by teto** [F1bonacc1/process-compose#268]
## Feature Request
Add possibility of skipping the exit prompt
![image](https://github.com/user-attachments/assets/b9313e73-91d6-4933-b365-bbc15dbe59d7)
it's an extra key that slows me down

#### Use Case:
I am iterating over my process-compose.yaml a lot and it keeps asking me wether I want to exit while I am sure I want to exit. Anyhow I use process-compose only for development purposes so there is rarely a case where I dont want to exit.

#### Proposed Change:
Ideally it would be a flag in ~/.config/process-compose/settings.yaml but I dont mind any solution really, a CLI flag or an environment variable would already be helpful

#### Who Benefits From The Change(s)?
me ?

#### Alternative Approaches
add a `quit!` shortcut one could map in config/process-compose/shortcuts.yaml ? 
```
  quit!:
    description: Force Quit
    shortcut: F10
```

**Comment by F1bonacc1** [comment]
Added in v1.40.0
```yaml
#XDG_CONFIG_HOME/process-compose/settings.yaml

theme: Cobalt
sort:
    by: NAME
    isReversed: false
disable_exit_confirmation: false # if true, will disable the TUI exit confirmation dialog
```
