### ISSUE TITLE
Dynamic port number for readines_probe when using multiple replicas

### ISSUE THREAD

**Issue by functoria** [F1bonacc1/process-compose#277]
Hi, 
I'm starting multiple replicas of the same web server process using the PC_REPLICA_NUM to inject the listening port number:

```
  my-web-app:
    replicas: 2
    command: |
      java -jar \
          -Dspring.profiles.active= \
          -Dspring.config.location=${APP_CONFIG_FILE} \
          -Dserver.port=808$$PC_REPLICA_NUM \
          -Xms${APP_MEM_XMS} \
          -Xmx${APP_MEM_XMX} \
          -Xss${APP_MEM_XSS} \
          ${APP_BINARY}
    availability:
      restart: on_failure
```
while the interpolation in the above case seems to work, when I'm trying to use the same variable for the `readiness_probe`, The `PC_REPLICA_NUM` variable is no longer correctly interpolated:

```
readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/api/management/health"
        port: 808$$PC_REPLICA_NUM  # <---What should I use here?
      initial_delay_seconds: 5
      period_seconds: 5
      timeout_seconds: 20
      success_threshold: 1
      failure_threshold: 3
```
and the process is terminated because the probe doesn't use the correct port.

Update: I've tried several interpolation patterns with no success and it looks like the actual value of `PC_REPLICA_NUM` variable is not available for `readiness_probe` or `liveness_probe` interpolation (always empty). Is this by design?

**Comment by F1bonacc1** [comment]
Hey @functoria,

As you know, evironment variables (global, process, and special cases like `PC_REPLICA_NUM`) are passed to the running process (`command`). Since readiness probe is not that, it requires special treatment and is not supported today.

What I can do to support that is add special directives to the templating engine so you will be able to achieve something similar to:
```yaml
readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/api/management/health"
        port: 808{{ replica }} # <--- this
```
The issue with this approach is that it won't support manual scaling (`F2` or `process-compose process scale proc_name 2`) if this is an acceptable tradeoff I can work on that for the next release.
