### ISSUE TITLE
[Defect] `process-compose project update` can't update when `processes` is empty list

### ISSUE THREAD

**Issue by misuzu** [F1bonacc1/process-compose#284]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

- [X] Included the relevant configuration snippet
- [X] Included the relevant process-compose log (log location: `process-compose info`)
- [X] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Steps or code to reproduce the issue:
1. create two configs:
```
cat <<'EOF' > /tmp/test-config-0.yaml
version: "0.5"

processes:
EOF
cat <<'EOF' > /tmp/test-config-1.yaml
version: "0.5"

processes:
  hello:
    command: echo 'Hello World'
  pc:
    command: echo 'From Process Compose'
    depends_on:
      hello:
        condition: process_completed
EOF
```
2. run process-compose with the first config
```
process-compose up --keep-project -f /tmp/test-config-0.yaml
```
3. update running process-compose instance using the second config
```
process-compose project update -f /tmp/test-config-1.yaml
```
#### Expected result:
The `hello` and `pc` appear in the TUI, the `project update` exits without errors.

#### Actual result:
The TUI shows panics for a short time and the `project update` command exits with an error:
```
% process-compose project update -f /tmp/test-config-1.yaml
24-12-10 20:55:00.271 FTL Failed to update project error=EOF
% cat /tmp/process-compose-misuzu.log
24-12-10 20:54:55.068 INF Process Compose v1.40.1
24-12-10 20:54:55.068 INF Loaded project from /tmp/test-config-0.yaml
24-12-10 20:54:55.068 INF Global shell command: bash -c
24-12-10 20:54:55.069 INF start http server listening :8080
24-12-10 20:54:55.069 DBG Spinning up 0 processes. Order: []
24-12-10 20:54:55.069 INF Project completed
24-12-10 20:55:00.270 DBG Process hello is new
24-12-10 20:55:00.270 DBG Process pc is new
```
When starting with `/tmp/test-config-1.yaml` and updating to `/tmp/test-config-0.yaml` everything seems to be fine.
