### ISSUE TITLE
Environment variables unavailable in `liveness_probe`

### ISSUE THREAD

**Issue by zilti** [F1bonacc1/process-compose#316]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

- [X] Included the relevant configuration snippet
- [X] Included the relevant process-compose log (log location: `process-compose info`)
- [X] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Version of `process-compose`:

v1.46.0

#### OS environment:

nixos

#### Steps or code to reproduce the issue:

```yaml
version: "0.5"
is_strict: true

log_location: ./logs/process-compose.log

env_cmds:
  PG: "echo $${PG:-$${PWD}/dev-server/postgres}"
  PGDATA: "echo $${PGDATA:-./data}"
  DB_NAME: "echo $${SALUS_DB_NAME:-test_template}"
  DB_USER: "echo $${SALUS_DB_USER:-test_user}"
  RESOURCES: "echo $${RESOURCES:-${PWD}/module/common/resources}"
  RESET_SALUS_TEST_FROM_TEMPLATE: "echo $${RESET_SALUS_TEST_FROM_TEMPLATE:-1}"

processes:

  postgresql:
    command: pg_ctl start -o "-k $${PG}"
    is_daemon: true
    shutdown:
      command: pg_ctl stop -o "-k $${PG}"
    liveness_probe:
      exec:
        command: pg_isready -h "$${PG}" -U "$${DB_USER}" -d "$${DB_NAME}"

```

#### Expected result:

`liveness_probe` runs and succeeds as expected, with the environment variables expanded.

#### Actual result:

Inside the liveness_probe `command`, the environment variable references are expanded to spaces, instead of the values stored in the variables.
