### ISSUE TITLE
Process not stopped

### ISSUE THREAD

**Issue by shyim** [F1bonacc1/process-compose#33]
I am starting a PHP-FPM server using process-compose and after stopping process-compose its still active.

My config:

```
processes:
  phpfpm-web:
    command: /Users/shyim/Downloads/start.sh
```

My start.sh

```
#!/usr/bin/env bash

exec /nix/store/770sz2xzliv4xf3z7mgmhj1kbc3asy60-php-with-extensions-8.1.13/bin/php-fpm -F -y /nix/store/ib4r50ck8gnk3jviscz4d0rbr08x3qsh-phpfpm-web.conf -c /nix/store/13gh8w0v5ps7xj5lqwndld0in3bmzsc0-php.ini
```

The `-F` parameter disables deamonize of php-fpm, but for some reason its not stopped.

I started process compose and killed the process by own and it works.

**Comment by thenonameguy** [comment]
Hey @shyim! 

Assuming `process-compose` sends the shutdown signal correctly, you can always force the process to be force-killed:
```
phpfpm-web:
  command: /Users/shyim/Downloads/start.sh
  shutdown:
    signal: 9 # SIGKILL, do not trust handling of SIGTERM correctly
```
You are already using `exec` correctly, so the signal should go straight to `php-fpm`, can you try it with this?

**Comment by shyim** [comment]
Force killing does not help as the php-fpm childs still alive

**Comment by thenonameguy** [comment]
It seems this is a common problem with `php-fpm`:
https://github.com/usabilla/php-docker-template/issues/96

Not a process-compose issue.

**Comment by shyim** [comment]
I tried multiple signals non of them are working 🙈 

```
processes:
  phpfpm-web:
    command: /Users/shyim/Downloads/start.sh
    shutdown:
      signal: 3
```

kill -3 pid works
