### ISSUE TITLE
fails to run in docker because user is nil

### ISSUE THREAD

**Issue by dzmitry-lahoda** [F1bonacc1/process-compose#84]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] Included the relevant configuration snippet
- [x] Included the relevant process-compose log (log location: `process-compose info`)
- [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Version of `process-compose`:

```
 docker run -it --entrypoint bash composablefi/devnet-xc:f110a75b84068c72c0d6589d964649547c0f9c74 
````

```
bash-5.2# cat devnet-xc-background
#!/nix/store/a7f7xfp9wyghf44yv6l6fv9dfw492hd3-bash-5.2-p15/bin/bash
set -o errexit
set -o nounset
set -o pipefail

export PATH="/nix/store/k01vbwj28s01da6f95r7qkiw2c56p52f-process-compose-0.51.4/bin:$PATH"

cat /nix/store/f50cr9qh6lc7cawbz8dbmf6nj9pl7k5k-devnet-xc-background.yaml
export PC_CONFIG_FILES=/nix/store/f50cr9qh6lc7cawbz8dbmf6nj9pl7k5k-devnet-xc-background.yaml
export PC_DISABLE_TUI=true
exec process-compose -p 8080 "$@"

bash-5.2# PATH="/nix/store/k01vbwj28s01da6f95r7qkiw2c56p52f-process-compose-0.51.4/bin:$PATH"
bash-5.2# 
bash-5.2# process-compose    
{"level":"fatal","error":"user: lookup userid 0: no such file or directory","time":"2023-08-04T00:27:45Z","message":"Failed to retrieve user info"}
bash-5.2# process-comepose --version
bash: process-comepose: command not found
bash-5.2# ^[[A^C
bash-5.2# process-compose --version
{"level":"fatal","error":"user: lookup userid 0: no such file or directory","time":"2023-08-04T00:28:00Z","message":"Failed to retrieve user info"}
bash-5.2# process-compose version      
{"level":"fatal","error":"user: lookup userid 0: no such file or directory","time":"2023-08-04T00:28:09Z","message":"Failed to retrieve user info"}
bash-5.2# process-compose -v       
{"level":"fatal","error":"user: lookup userid 0: no such file or directory","time":"2023-08-04T00:28:18Z","message":"Failed to retrieve user info"}
bash-5.2# process-compose -version 
{"level":"fatal","error":"user: lookup userid 0: no such file or directory","time":"2023-08-04T00:28:22Z","message":"Failed to retrieve user info"}
bash-5.2# process-compose --help   
{"level":"fatal","error":"user: lookup userid 0: no such file or directory","time":"2023-08-04T00:28:28Z","message":"Failed to retrieve user info"}
bash-5.2# 
```

#### OS environment:

Docker.

#### Steps or code to reproduce the issue:

```
 docker run -it  composablefi/devnet-xc:main 
```

#### Expected result:

Runs or other error.

#### Actual result:

```
actions-runner@Ubuntu-2204-jammy-amd64-base:~$ docker run -it  composablefi/devnet-xc:f110a75b84068c72c0d6589d964649547c0f9c74 
processes:
  centauri:
    availability:
      restart: on_failure
    command: /nix/store/4l88isl2fhib4zsdq94xx3sspjs70jsg-centaurid-gen/bin/centaurid-gen
    log_location: /tmp/composable-devnet/centauri.log
    readiness_probe:
      failure_threshold: 3
      http_get:
        host: 127.0.0.1
        path: /
        port: 26657
        scheme: http
      initial_delay_seconds: 0
      period_seconds: 10
      success_threshold: 1
      timeout_seconds: 3
  centauri-init:
    availability:
      restart: on_failure
    command: /nix/store/65jjn2ckp8qa32k935ill8liqifx4l4x-centaurid-init/bin/centaurid-init
    depends_on:
      centauri:
        condition: process_healthy
    log_location: /tmp/composable-devnet/centauri-init.log
  composable:
    availability:
      restart: on_failure
    command: /nix/store/07q9wz30dchv8s64zxqfdzhb4nbbvcvw-zombienet-composable-centauri-b/bin/zombienet-composable-centauri-b
    log_location: /tmp/composable-devnet/composable.log
    readiness_probe:
      exec:
        command: |
          curl --header "Content-Type: application/json" --data '{"id":1, "jsonrpc":"2.0", "method" : "assets_listAssets"}' http://127.0.0.1:32201
      failure_threshold: 8
      initial_delay_seconds: 32
      period_seconds: 8
      success_threshold: 1
      timeout_seconds: 2
  composable-picasso-ibc-channels-init:
    availability:
      restart: on_failure
    command: "HOME=\"/tmp/composable-devnet/composable-picasso-ibc\"\nexport HOME       \nRUST_LOG=\"hyperspace=info,hyperspace_parachain=debug,hyperspace_cosmos=debug\"\nexport RUST_LOG\n/nix/store/f6anaxjgf6i33380mz03njaks17hcvb3-hyperspace-composable-rococo-picasso-rococo/bin/hyperspace create-channel --config-a /tmp/composable-devnet/composable-picasso-ibc/config-chain-a.toml --config-b /tmp/composable-devnet/composable-picasso-ibc/config-chain-b.toml --config-core /tmp/composable-devnet/composable-picasso-ibc/config-core.toml --delay-period 10 --port-id transfer --version ics20-1 --order unordered\n"
    depends_on:
      composable-picasso-ibc-connection-init:
        condition: process_completed_successfully
    log_location: /tmp/composable-devnet/composable-picasso-ibc-channels-init.log
  composable-picasso-ibc-connection-init:
    availability:
      restart: on_failure
    command: "HOME=\"/tmp/composable-devnet/composable-picasso-ibc\"\nexport HOME                \nRUST_LOG=\"hyperspace=info,hyperspace_parachain=debug,hyperspace_cosmos=debug\"\nexport RUST_LOG      \n/nix/store/f6anaxjgf6i33380mz03njaks17hcvb3-hyperspace-composable-rococo-picasso-rococo/bin/hyperspace create-connection --config-a /tmp/composable-devnet/composable-picasso-ibc/config-chain-a.toml --config-b /tmp/composable-devnet/composable-picasso-ibc/config-chain-b.toml --config-core /tmp/composable-devnet/composable-picasso-ibc/config-core.toml --delay-period 10\n"
    depends_on:
      composable-picasso-ibc-init:
        condition: process_completed_successfully
    log_location: /tmp/composable-devnet/composable-picasso-ibc-connection-init.log
  composable-picasso-ibc-init:
    availability:
      restart: on_failure
    command: /nix/store/ag4h4pzbsfsybxfkq9vwxnhrvpy44lbc-composable-picasso-ibc-init/bin/composable-picasso-ibc-init
    depends_on:
      composable:
        condition: process_healthy
      picasso:
        condition: process_healthy
      picasso-centauri-ibc-channels-init:
        condition: process_completed_successfully
    log_location: /tmp/composable-devnet/composable-picasso-ibc-init.log
  composable-picasso-ibc-relay:
    availability:
      restart: on_failure
    command: /nix/store/rps5vp8r12ppn268hq7zldk4hx42jb5c-composable-picasso-ibc-relay/bin/composable-picasso-ibc-relay
    depends_on:
      composable-picasso-ibc-channels-init:
        condition: process_completed_successfully
    log_location: /tmp/composable-devnet/composable-picasso-ibc-relay.log
  osmosis:
    command: /nix/store/vpg6764j5wagzmlqml3vmsh3288yh8ig-osmosisd-gen/bin/osmosisd-gen
    log_location: /tmp/composable-devnet/osmosis.log
    readiness_probe:
      failure_threshold: 3
      http_get:
        host: 127.0.0.1
        path: /
        port: 36657
        scheme: http
      initial_delay_seconds: 0
      period_seconds: 10
      success_threshold: 1
      timeout_seconds: 3
  osmosis-centauri-hermes-init:
    availability:
      restart: on_failure
    command: /nix/store/pbglg0a7f9a52b0f7af15g3r8cc8698m-osmosis-centauri-hermes-init/bin/osmosis-centauri-hermes-init
    depends_on:
      centauri-init:
        condition: process_completed_successfully
      osmosis:
        condition: process_healthy
      picasso-centauri-ibc-channels-init:
        condition: process_completed_successfully
    log_location: /tmp/composable-devnet/osmosis-centauri-hermes-init.log
  osmosis-centauri-hermes-relay:
    availability:
      restart: on_failure
    command: /nix/store/dal3sw1j21vvrv1ib6l8hxcsirc1na6r-osmosis-centauri-hermes-relay/bin/osmosis-centauri-hermes-relay
    depends_on:
      osmosis-centauri-hermes-init:
        condition: process_completed_successfully
    log_location: /tmp/composable-devnet/osmosis-centauri-hermes-relay.log
  osmosis-init:
    availability:
      restart: on_failure
    command: /nix/store/ggrnlgq6rfwhp5r9h067l8kwi358qf8s-osmosisd-init/bin/osmosisd-init
    depends_on:
      osmosis:
        condition: process_healthy
    log_location: /tmp/composable-devnet/osmosis-init.log
  picasso:
    availability:
      restart: on_failure
    command: /nix/store/3khkmb88vyw376agfczi0k0j2hfqr62h-zombienet-rococo-local-picasso-dev/bin/zombienet-rococo-local-picasso-dev
    log_location: /tmp/composable-devnet/picasso.log
    readiness_probe:
      exec:
        command: |
          curl --header "Content-Type: application/json" --data '{"id":1, "jsonrpc":"2.0", "method" : "assets_listAssets"}' http://127.0.0.1:32200
      failure_threshold: 8
      initial_delay_seconds: 32
      period_seconds: 8
      success_threshold: 1
      timeout_seconds: 2
  picasso-centauri-ibc-channels-init:
    availability:
      restart: on_failure
    command: /nix/store/w9c4fcnzkkwjvqzlxms63fzlp4warksd-picasso-centauri-ibc-channels-init/bin/picasso-centauri-ibc-channels-init
    depends_on:
      picasso-centauri-ibc-connection-init:
        condition: process_completed_successfully
    log_location: /tmp/composable-devnet/picasso-centauri-ibc-channels-init.log
  picasso-centauri-ibc-connection-init:
    availability:
      restart: on_failure
    command: /nix/store/g0kknc92nbn99h5wgk7sxf8zlw4v9rb2-picasso-centauri-ibc-connection-init/bin/picasso-centauri-ibc-connection-init
    depends_on:
      picasso-centauri-ibc-init:
        condition: process_completed_successfully
    log_location: /tmp/composable-devnet/picasso-centauri-ibc-connection-init.log
  picasso-centauri-ibc-init:
    availability:
      restart: on_failure
    command: /nix/store/parh7f1mvlkjyfs1kz0xxmp64lqmv96n-picasso-centauri-ibc-init/bin/picasso-centauri-ibc-init
    depends_on:
      centauri:
        condition: process_healthy
      centauri-init:
        condition: process_completed_successfully
      picasso:
        condition: process_healthy
    log_location: /tmp/composable-devnet/picasso-centauri-ibc-init.log
  picasso-centauri-ibc-relay:
    availability:
      restart: on_failure
    command: /nix/store/9nwl712053i5zgb8qdxfammx288091gi-picasso-centauri-ibc-relay/bin/picasso-centauri-ibc-relay
    depends_on:
      picasso-centauri-ibc-channels-init:
        condition: process_completed_successfully
    log_location: /tmp/composable-devnet/picasso-centauri-ibc-relay.log
shell:
  shell_argument: -c
  shell_command: /nix/store/a7f7xfp9wyghf44yv6l6fv9dfw492hd3-bash-5.2-p15/bin/bash
{"level":"fatal","error":"user: lookup userid 0: no such file or directory","time":"2023-08-04T00:26:18Z","message":"Failed to retrieve user info"}
```
