### ISSUE TITLE
Split log files by day or size (log rolling)

### ISSUE THREAD

**Issue by outstanding1301** [F1bonacc1/process-compose#94]
## Feature Request

Split log files by day or size (log rolling)

#### Use Case:

- Prevent the log file from becoming too large.  
  - If the application is too talkative, there is a risk that the log file size will grow infinitely.
- Effective log management.
  - Quick access to logs from a specific date.

#### Proposed Change:

in `process-compose.yml`
```yml
log_location: logs/log.txt
log_level: debug
```

to

```yml
log_location: logs  # it must be a directory
log_level: debug
log_rolling:
  format: log-{day}.txt  # or log-{index}.txt / log-{day}_{index}.txt ...
  day: 1  # Interval for rolling log files. [logs/log.txt-2023-09-21] [[logs/log.txt-2023-09-22] ... 
  size: 100MB  # File size for rolling files. [logs/log.txt-1] [logs/log.txt-2] ...
```

#### Who Benefits From The Change(s)?
People who will keep this application running for a long time.

#### Alternative Approaches
I think it would be great if this amazing app has more options to manage log.

**Comment by F1bonacc1** [comment]
Hi @outstanding1301 

Thank you for creating this feature request.
I think it will be better to put a timestamp in the log file since we can't guarantee that the rotation size will create a file each `{day}`.
I will also add the same configuration to each process (optional and backward compatible):
```yaml
log_rotation:
  max_size_mb: 1 # the max size in MB of the logfile before it's rolled
  max_age_days: 3 # the max age in days to keep a logfile
  max_backups: 3 # the max number of rolled files to keep
  compress: true # determines if the rotated log files should be compressed using gzip. The default is not to perform compression.
```
