### ISSUE TITLE
Log formatting

### ISSUE THREAD

**Issue by outstanding1301** [F1bonacc1/process-compose#95]
## Feature Request

Log formatting
- process-compose write log like  
`{"level":"error","process":"someapp","replica":0,"message":"some application message"}`
- i think we can use thoese keys(level, process, ...) to format log 

#### Use Case:
in `process-compose.yml`
```yml
log_location: logs/log.log
log_level: debug
log_format: "[{process}-{replica}] {asctime}  {level} --- {message}"
```

-->
```txt
[someapp-0] 2023-09-21  error --- some application message
```
