### ISSUE TITLE
Is there a community around process compose?

### ISSUE THREAD

**Issue by carlotm** [F1bonacc1/process-compose#96]
Just wanted to know what is the place (if any) to ask questions about this awesome project.

Thank you for the effort and kudos.

Cheers!

**Comment by F1bonacc1** [comment]
Hey @carlotm,
Thank you for trying this project out. Glad you like it.

I think here would be a good place to start.
If you were thinking about something more "community like", I can create a discord channel.

**Comment by carlotm** [comment]
I'll try to ask here, and you can decide if that could spark a channel :)

- Is process compose suitable for "one shot" commands?
 
I have this scenario:
A postgresql process `P`
A solr process `S`
A web server process `W`
A one shot process `I` which creates postgres users and solr indexes.

I starts when `P` and `S` are healthy
`W` starts when `P` and `S` are healthy and `I` as exited succesfully

Problem is `I` should be run only the first time.

Thinking about that, i could make `I` idempotent, and run it every time the system start,
or is there a better way to handle processes specific commands that should be run only once?

Thank you, cheers!

**Comment by thenonameguy** [comment]
Hey @carlotm !

I just implemented something similar (without SOLR) this week:
```yaml
processes:
  postgres:
    availability:
      restart: on_failure
    command: /nix/store/vd6cl86dbbpnbnn3ld2mab8b8j2awvl1-start-postgres/bin/start-postgres
    readiness_probe:
      exec:
        command: /nix/store/zdlq5764lazkhmyjch502sdaf3w2qmzl-postgresql-and-plugins-15.3/bin/pg_isready
          -h $PGDATA -d template1
      failure_threshold: 5
      initial_delay_seconds: 2
      period_seconds: 10
      success_threshold: 1
      timeout_seconds: 4
    shutdown:
      signal: 2
  seed-postgres:
    availability:
      restart: 'no'
    command: "/nix/store/7i9c8b5sjsllm4154db74y0szc06pqrj-zstd-1.5.5-bin/bin/zstd\
      \ -dc db_dumps/Adventureworks.sql.zst | \\\n   /nix/store/yimwyqmbynicligkgsrlc8qsfhrgzaby-postgresql-15.3/bin/psql\
      \ -h 127.0.0.1 -U schemamap_test -v ON_ERROR_STOP=1 --single-transaction schemamap_test\n"
    depends_on:
      postgres:
        condition: process_healthy
```
Here is the [`.nix` source](https://github.com/schemamap/schemamap/blob/main/devenv.nix#L78-L91) for it.

Idempotency is the way to go. If you want to be more fancy, you can write a seed hash into each store, check for it for equality in your seed script and then truncate and reload the data in case it's not equal. This way you can Ctrl-R the seed script process if you `git pull`/change the data locally.
