### ISSUE TITLE
Allow processes with same name but in different namespace

### ISSUE THREAD

**Issue by shivaraj-bh** [F1bonacc1/process-compose#97]
#### Use Case: 
Consider two process in different namespace but with similar functionality, it could be more readable if allowed to have same name.

#### Who Benefits From The Change(s)? 
will be useful here: https://github.com/juspay/services-flake/pull/57
This change can be opinionated.

**Comment by F1bonacc1** [comment]
Hi @shivaraj-bh,

That's a proposal that makes a lot of sense.
The downside is that it will break backward compatibility. As you know the `namespace` key is part of the process:
```yaml
processes:
  p1:
    command: c1
    namespace: n1
  p2:
    command: c2
    namespace: n2
```
Changing `p2` to `p1` will fail parsing on the `yaml` level.
The YAML spec does not allow for duplicate keys in a mapping node.

There are a few bad options that I see:

**Option 1:**
```yaml
processes:
  n1:
    p1:
      command: c1
  n2:
    p1:
      command: c2
```
Which breaks backward compatibility.

**Option2:**
Add NS prefix with a delimiter.
```yaml
processes:
  n1::p1:
    command: c1
    namespace: n1
  n2::p1:
    command: c2
    namespace: ABCD # kept for BW compatibility, but will be replaced with `n2` in code.
```
Feels not intuitive and hacky.

**Option3:**
Convert processes to a list.
```yaml
processes:
  - p1:
    command: c1
    namespace: n1
  - p1:
    command: c2
    namespace: n2
```
Also breaks backward compatibility and for long enough `compose.yaml` files there will be more than 1 `default.p1` processes.

Do you see any other options that I am missing?
