### ISSUE TITLE
How can I debug erlang rebar3 shell not working?

### ISSUE THREAD

**Issue by carlotm** [F1bonacc1/process-compose#98]
Hi all,
one of the processes I am trying to execute doesn't work in process-compose.
What can I do to find the cause?

The command I am trying to run is `rebar3 shell`
If I run it from the command line it works correctly, If I run it using process-compose I got this error:

![Screenshot_2023-10-26_16-38-10](https://github.com/F1bonacc1/process-compose/assets/64407038/c41be311-bc57-44b2-81ca-1a7be91f5842)

My process-compose file is:

```
version: "0.5"

processes:
  frontend:
    command: "devbox run frontend:build"
  postgresql:
    command: "pg_ctl start -o \"-k $PGHOST\""
    is_daemon: true
    readiness_probe:
      exec:
        command: pg_isready
    shutdown:
      command: "pg_ctl stop -m fast"
    availability:
      restart: "always"
  db_init:
    command: "[ -f .db.done ] || devbox run db"
    depends_on:
      postgresql:
        condition: process_healthy
  rebar_shell:
    command: "rebar3 shell"
    is_daemon: true
    availability:
      restart: "always"
    dedens_on:
      db_init:
        condition: process_completed
      postgresql:
        condition: process_healthy
```
